### ISSUE TITLE
did-jwt & jose

### ISSUE THREAD

**Issue by JonasKruckenberg** [ceramicnetwork/js-dag-jose#10]
Hello, me again. I figured that I probably should be discussing things here, instead if the specs repo. 
Turned out that I was just expecting this module to work differently so now it's working for me too.
As my playground implementation uses the [Jose](https://github.com/panva/jose) I wondered why you are using did-jwt. I it because the DID functionality allows for easier integration of ceramic with a blockchain?
Because for example adding some sort of JWKS support would be pretty beneficial for this module right?
Let me know what you think
Edit: I also was about to offer my help with encryption when I saw that you already did that, awesome 👍

**Comment by JonasKruckenberg** [comment]
Good idea yeah, maybe a library that can also interface with the ipfs keystore for keys or something 🤔

**Comment by JonasKruckenberg** [comment]
Not bad, looks like I might actually be able to switch over to your library for my use case.
One question though, how is he-did doing the cntent dag node thing?
Without looking into the created days I'd assumethe content is just the raw encrypted bytes and the new includes a link and the decryption info.
Or are you putting all the data into an identity cid as you mentioned?

**Comment by oed** [comment]
For JWS the payload is encoded into a dag-cbor block and we just sign the normal CID.
For JWE the cleartext is encoded into dag-cbor and we encrypt the identity CID.

Happy to add options for other configurations if that is desirable!

**Comment by JonasKruckenberg** [comment]
I think we can close this now :)
