### ISSUE TITLE
Example with more detail on metadata and composition for DID/personal datastore use cases

### ISSUE THREAD

**Issue by csuwildcat** [ceramicnetwork/js-dag-jose#19]
I was hoping to kick the tires on this and was looking for examples of the following:

1. What do the unencoded JW*s look like for use relative to a given DID?
2. Is there an example where the JW* doesn't include a signature at all?

**Comment by oed** [comment]
Please refer to the official IETF JOSE specs and https://ipld.io/specs/codecs/dag-jose/spec/
