### ISSUE TITLE
Export DagJWS and DagJWE types 

### ISSUE THREAD

**Issue by achingbrain** [ceramicnetwork/js-dag-jose#26]
# Description

v1 of this module exported the [DagJWS](https://github.com/ceramicnetwork/js-dag-jose/blob/3ad7f815bb93d1d2ffd250c4cdf83cc3c13cf2cc/src/index.ts#L2) and [DagJWE](https://github.com/ceramicnetwork/js-dag-jose/blob/3ad7f815bb93d1d2ffd250c4cdf83cc3c13cf2cc/src/index.ts#L4) types but are not exported in v2.

This breaks [code that uses those types](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/dag/get.js#L49).

Please can they be exported again?

# Technical Information

`DagJWS` and `DagJWE` types need to be exported from `index.js`.

**Comment by ukstv** [comment]
Sure, they can. Please, give me some time to do that. How urgent do you feel this is?

**Comment by achingbrain** [comment]
It's not super urgent in that nothing is broken as the old version still works, but it is preventing me from updating dag-jose in IPFS.  The upgrade is important to shift more of the stack onto ESM.
