### ISSUE TITLE
error: s.replace is not a function

### ISSUE THREAD

**Issue by gouranshforcebolt** [ceramicnetwork/js-dag-jose#27]
Hi,
I am getting an error "TypeError: s.replace is not a function" from line:
const decryptedData = await decryptJWE(block.value, asymDecrypter)
![Screenshot from 2022-07-27 19-34-58](https://user-images.githubusercontent.com/103058351/181268469-df91fe44-2fe5-48ea-b24c-d9ebae0196ec.png)

Can anyone please help

**Comment by oed** [comment]
Could you share the code you are using please?

**Comment by gouranshforcebolt** [comment]
import * as React from "react";
import { randomBytes } from "@stablelib/random";
import { generateKeyPairFromSeed } from "@stablelib/x25519";

// JWT & utilities
import {
  x25519Encrypter,
  x25519Decrypter,
  decryptJWE,
  createJWE
} from "did-jwt";
import { decodeCleartext, prepareCleartext } from "dag-jose-utils";

import * as Block from "multiformats/block";
import { sha256 } from "multiformats/hashes/sha2";
import * as dagJose from "dag-jose";
import * as dagCbor from "@ipld/dag-cbor"; // for decoding the signed payload

interface IEncryptFileProps {}

const EncryptFile: React.FunctionComponent<IEncryptFileProps> = (props) => {
  const store = new Map();


  async function asymmetric() {
    // Encrypt and store a payload using a public key
    const storeEncrypted = async (payload: any, pubkey: any) => {
      const asymEncrypter = x25519Encrypter(pubkey);
      // prepares a cleartext object to be encrypted in a JWE
      const cleartext = await prepareCleartext(payload);
      // encrypt into JWE container layout using public key
      const jwe = await createJWE(cleartext, [asymEncrypter]);
      console.log(jwe, "iijwe");
      // create an IPLD Block that has the CID:Bytes:Value triple
      const block = await Block.encode({
        value: jwe,
        codec: dagJose,
        hasher: sha256
      });
      console.log(block, "iiblock");
      console.log(`Encrypted block CID: \u001b[32m${block.cid}\u001b[39m`);
      console.log("Encrypted block contents:\n", block.value);
      // store the block, this could be in IPFS or any other CID:Bytes block store
      store.set(block.cid.toString(), block.bytes);
      return block.cid;
    };

    // Load an encrypted block from a CID and decrypt the payload using a secret key
    const loadEncrypted = async (cid: any, privkey: any) => {
      const asymDecrypter = x25519Decrypter(privkey);
      console.log(store, 'iistore')
      const bytes = store.get(cid.toString());
      console.log(asymDecrypter, bytes, "iiab");
      //   decode the DAG-JOSE envelope
      const block: any = await Block.create({
        cid,
        bytes,
        codec: dagCbor,
        hasher: sha256
      });

      console.log(block, "iijwecc");

      if (!block.cid.equals(cid)) {
        console.log("iinerror");
        throw new Error("CID mismatch");
      }
      // decrypt the encrypted payload
      const decryptedData = await decryptJWE(block.value, asymDecrypter);
      return decodeCleartext(decryptedData);
    };

    const privkey = randomBytes(32);
    console.log(privkey, 'iikeypp')
    // generate a public key from the existing private key
    const pubkey = generateKeyPairFromSeed(privkey).publicKey;
    const secretz = { my: "secret message" };
    console.log(
      "Encrypting and storing secret with public key:\u001b[1m",
      secretz,
      "\u001b[22m"
    );
    const cid = await storeEncrypted(secretz, pubkey);
    console.log(cid, privkey, "iikeys");

    const decoded = await loadEncrypted(cid, privkey);
    console.log(
      "Loaded and decrypted block content with private key:\u001b[1m",
      decoded,
      "\u001b[22m"
    );
  }

  asymmetric()
    .then((value) => {
      console.log("iivalue", value);
    })
    .catch((e) => {
      console.error(e.stack);
    });

  return <div></div>;
};

export default EncryptFile;



Here is the code I am using.
